In [56]:
import numpy as np
import pandas as pd

In [25]:
gxdc=pd.read_csv(r'C:\数据练习\5数据的科学运算\data1.csv')

In [26]:
gxdc.head()

orderid  bikeid  userid        start_time  start_location_x  \
0    78387  158357   10080  2016-08-20 06:57           121.348   
1   891333   92776    6605  2016-08-29 19:09           121.508   
2  1106623  152045    8876  2016-08-13 16:17           121.383   
3  1389484  196259   10648  2016-08-23 21:34           121.484   
4   188537   78208   11735  2016-08-16 07:32           121.407   

   start_location_y          end_time  end_location_x  end_location_y  \
0            31.389  2016-08-20 07:04         121.357          31.388   
1            31.279  2016-08-29 19:31         121.489          31.271   
2            31.254  2016-08-13 16:36         121.405          31.248   
3            31.320  2016-08-23 21:43         121.471          31.325   
4            31.292  2016-08-16 07:41         121.418          31.288   

                                               track  
0  121.347,31.392#121.348,31.389#121.349,31.390#1...  
1  121.489,31.270#121.489,31.271#121.490,31.270#1...  
2  121.381,31.251#121.382,31.251#121.382,31.252#1...  
3  121.471,31.325#121.472,31.325#121.473,31.324#1...  
4  121.407,31.291#121.407,31.292#121.408,31.291#1...

In [88]:
ly=pd.read_csv(r'C:/数据练习/5数据的科学运算/data2.csv')
ly.head()

Unnamed: 0 出发地   目的地     价格      节省  \
0           0  哈尔滨   北海  2208.0  650.0   
1           1   成都  泸沽湖  1145.0  376.0   
2           2   广州   沈阳  2702.0  618.0   
3           3   上海  九寨沟  1954.0  484.0   
4           4   广州   天津  1608.0  422.0   

                                       路线名                       酒店  \
0     哈尔滨-北海3天2晚 | 入住北海祥丰嘉年华大酒店 + 春秋航空往返机票   北海祥丰嘉年华大酒店 舒适型 4.7分/5分   
1    成都-泸沽湖3天2晚 | 入住7天酒店丽江古城中心店 + 成都航空往返机票  7天酒店丽江古城中心店 经济型 4.0分/5分   
2     广州-沈阳3天2晚 | 入住沈阳中煤宾馆 + 南方航空/深圳航空往返机票       沈阳中煤宾馆 舒适型 4.5分/5分   
3        上海-九寨沟3天2晚 | 入住红原芸谊大酒店 + 成都航空往返机票      红原芸谊大酒店 舒适型 4.6分/5分   
4  广州-天津3天2晚 | 入住天津逸海明珠大酒店 + 奥凯航空/海南航空往返机票    天津逸海明珠大酒店 高档型 4.1分/5分   

                           房间         去程航司 去程方式         去程时间         回程航司  \
0       标准双人间(双床) 双床 不含早 1间2晚  春秋航空 9C8741   直飞  17:10-21:50  春秋航空 9C8742   
1  经济房-不含早-限时特... 其他 不含早 1间2晚  成都航空 EU2237   直飞  19:45-21:20  成都航空 EU2738   
2          大床间(内宾) 大床 双早 1间2晚  南方航空 CZ6384   直飞  08:05-11:45  深圳航空 ZH9652   
3        豪华双床房[双早] 双床 双早 1间2晚  成都航空 EU6678   直飞  21:55-01:15  成都航空 EU6677   
4       豪华双床房(预付) 双床 不含早 1间2晚  奥凯航空 BK2787   直飞  06:55-10:00  海南航空 HU7201   

  回程方式          回程时间  
0    直飞  10:20-15:05  
1    直飞  23:30-01:05  
2    经停  08:20-13:05  
3    直飞  17:45-20:35  
4    直飞  20:15-23:25

In [7]:
data_excel_1=pd.read_excel(r'C:\数据练习\5数据的科学运算\data_excel.xlsx',sheet_name='工作表1',engine="openpyxl")
data_excel_2=pd.read_excel(r'C:\数据练习\5数据的科学运算\data_excel.xlsx',sheet_name='工作表2',engine="openpyxl")                         

C:\Users\User\AppData\Roaming\Python\Python36\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [8]:
data_excel_1

id  age  place
0   1   11     21
1   2   12     22
2   3   13     23
3   4   14     24
4   5   15     25
5   6   16     26
6   7   17     27
7   8   18     28
8   9   19     29
9  10   20     30

In [135]:
df_=pd.read_csv(r'C:/数据练习/5数据的科学运算/executive.csv')

In [136]:
df_=df_.groupby(by='sex').mean()

In [137]:
df_.reset_index(inplace=True)

In [138]:
df_

sex        age
0   女  48.907173
1   男  51.922720

In [62]:
df_['age'].sum()

291934

In [165]:
executive=pd.read_csv(r'C:/数据练习/5数据的科学运算/executive.csv',chunksize=100)
#executive.get_chunk(102)

In [70]:
#分块，累加
number=0
for c in executive:
    number+=c['age'].sum()
    

In [166]:
for c in executive:
    df_c=c.groupby(by='sex').mean()
    df_c.reset_index(inplace=True)
    print(df_c)

  sex        age
0   女  50.444444
1   男  51.879121
  sex        age
0   女  53.333333
1   男  50.868132
  sex        age
0   女  52.222222
1   男  52.439560
  sex        age
0   女  45.166667
1   男  50.808511
  sex        age
0   女  48.833333
1   男  51.215909
  sex        age
0   女  46.117647
1   男  50.385542
  sex        age
0   女  54.200000
1   男  53.866667
  sex        age
0   女  51.800000
1   男  54.042105
  sex        age
0   女  52.666667
1   男  54.412371
  sex        age
0   女  47.500000
1   男  53.520833
  sex        age
0   女  48.857143
1   男  50.881720
  sex        age
0   女  49.666667
1   男  53.148936
  sex        age
0   女  52.000000
1   男  52.681319
  sex        age
0   女  51.090909
1   男  50.415730
  sex        age
0   女  47.363636
1   男  51.831461
  sex        age
0   女  49.200000
1   男  53.126316
  sex        age
0   女  49.285714
1   男  52.666667
  sex    age
0   女  44.50
1   男  51.75
  sex        age
0   女  52.500000
1   男  51.520833
  sex        age
0   女  47.700000
1   男  52

In [163]:
cnt=0
for c in executive:
    if cnt==0:
        df_all=pd.DataFrame({'sex':[],'age':[]})
        df_all.reset_index(inplace=True)
        df_all.drop('index',axis=1,inplace=True)
    df_c=c.groupby(by='sex').mean()
    df_c.reset_index(inplace=True)
    df_all=pd.concat([df_all,df_c])
    cnt+=1

In [164]:
df_all

sex        age
0    女  50.444444
1    男  51.879121
0    女  53.333333
1    男  50.868132
0    女  52.222222
..  ..        ...
1    男  51.000000
0    女  51.200000
1    男  51.978947
0    女  46.375000
1    男  52.119048

[114 rows x 2 columns]

In [48]:
li=pd.Series(['a','b','b','d','e'])
li

0    a
1    b
2    b
3    d
4    e
dtype: object

In [12]:
dic=pd.Series({'a':100,'b':200,'c':300})
dic

a    100
b    200
c    300
dtype: int64

In [13]:
#None->真空值，空格不是空值
data=pd.Series({'a':None,'b':200,'c':300,'d':400})
data

a      NaN
b    200.0
c    300.0
d    400.0
dtype: float64

In [14]:
pd.isnull(data)

a     True
b    False
c    False
d    False
dtype: bool

In [16]:
d1=pd.Series([1,2,3,4,5])
d2=pd.Series([-1,-2,-3,-4,-5])
d1+d2

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [17]:
d11=pd.Series([1,2,3,4,5])
d22=pd.Series([-1,-2,-3,-4,-5,-6])
d11+d22

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    NaN
dtype: float64

In [26]:
d11=pd.Series([1,2,3,4,5])
d22=pd.Series([-1,-2,-3,-4,-5,-6])
d11*d22

0    -1.0
1    -4.0
2    -9.0
3   -16.0
4   -25.0
5     NaN
dtype: float64

In [18]:
df=pd.DataFrame({'A':[1,2,3],'B':[4,'5',6]})
df.loc[[1],'A']

1    2
Name: A, dtype: int64

In [19]:
df=pd.DataFrame({'A':['1',2,3],'B':[4,'5',6]})
df.loc[[1],'A']

1    2
Name: A, dtype: object

In [21]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,10).astype(float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
np.arange(1,10).astype(int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr=np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
arr.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr_3D.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
arr_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [21]:
arr_2D=np.array([[1,2,3],[4,5,6]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr_3D+arr_2D

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [14, 16, 18]],

       [[14, 16, 18],
        [20, 22, 24]]])

In [32]:
pd.datetime.today().month

C:\Users\User\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime instead.
  """Entry point for launching an IPython kernel.


5

In [33]:
import datetime

In [40]:
datetime.datetime.today().year

2022

In [51]:
gxdc.head()

orderid  bikeid  userid        start_time  start_location_x  \
0    78387  158357   10080  2016-08-20 06:57           121.348   
1   891333   92776    6605  2016-08-29 19:09           121.508   
2  1106623  152045    8876  2016-08-13 16:17           121.383   
3  1389484  196259   10648  2016-08-23 21:34           121.484   
4   188537   78208   11735  2016-08-16 07:32           121.407   

   start_location_y          end_time  end_location_x  end_location_y  \
0            31.389  2016-08-20 07:04         121.357          31.388   
1            31.279  2016-08-29 19:31         121.489          31.271   
2            31.254  2016-08-13 16:36         121.405          31.248   
3            31.320  2016-08-23 21:43         121.471          31.325   
4            31.292  2016-08-16 07:41         121.418          31.288   

                                               track  
0  121.347,31.392#121.348,31.389#121.349,31.390#1...  
1  121.489,31.270#121.489,31.271#121.490,31.270#1...  
2  121.381,31.251#121.382,31.251#121.382,31.252#1...  
3  121.471,31.325#121.472,31.325#121.473,31.324#1...  
4  121.407,31.291#121.407,31.292#121.408,31.291#1...

In [53]:
gxdc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102361 entries, 0 to 102360
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   orderid           102361 non-null  int64  
 1   bikeid            102361 non-null  int64  
 2   userid            102361 non-null  int64  
 3   start_time        102361 non-null  object 
 4   start_location_x  102361 non-null  float64
 5   start_location_y  102361 non-null  float64
 6   end_time          102361 non-null  object 
 7   end_location_x    102361 non-null  float64
 8   end_location_y    102361 non-null  float64
 9   track             102361 non-null  object 
dtypes: float64(4), int64(3), object(3)
memory usage: 7.8+ MB


In [57]:
start_time=pd.to_datetime(gxdc['start_time'])

In [58]:
end_time=pd.to_datetime(gxdc['end_time'])

In [59]:
np.max(end_time-start_time)


Timedelta('3 days 06:45:00')

In [60]:
np.min(end_time-start_time)

Timedelta('0 days 00:01:00')

In [ ]:
pd.to_datetime(end_time,unit='s',origin=pd.Timestamp('1970-01-01 08:00:00'))

In [66]:
gxdc.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...  
102356    False
102357    False
102358    False
102359    False
102360    False
Length: 102361, dtype: bool

In [68]:
gxdc.duplicated(subset='bikeid')

0         False
1         False
2         False
3         False
4         False
          ...  
102356     True
102357     True
102358    False
102359    False
102360     True
Length: 102361, dtype: bool

In [69]:
gxdc[gxdc.duplicated(subset='bikeid')]

orderid  bikeid  userid        start_time  start_location_x  \
972     1242500  210205    2691  2016-08-17 16:29           121.476   
1041    1191995  251348    2572  2016-08-23 17:40           121.415   
1133     347365   41056    7271  2016-08-18 12:46           121.384   
1204     889469  171241    9234  2016-08-20 21:19           121.414   
1374    1011809   57862    3692  2016-08-04 19:59           121.417   
...         ...     ...     ...               ...               ...   
102354   182261   16353    2628  2016-08-03 10:05           121.498   
102355   640008  329621   10791  2016-08-29 15:39           121.518   
102356  1479550  214335    1423  2016-08-28 18:03           121.478   
102357  1478273  160487    3067  2016-08-14 20:22           121.320   
102360   326987   63172    2547  2016-08-09 10:51           121.521   

        start_location_y          end_time  end_location_x  end_location_y  \
972               31.270  2016-08-17 16:40         121.464          31.267   
1041              31.197  2016-08-23 18:08         121.433          31.226   
1133              31.261  2016-08-18 13:02         121.382          31.245   
1204              31.269  2016-08-20 21:36         121.434          31.259   
1374              31.188  2016-08-04 20:06         121.410          31.186   
...                  ...               ...             ...             ...   
102354            31.288  2016-08-03 10:13         121.508          31.281   
102355            31.311  2016-08-29 15:48         121.523          31.322   
102356            31.297  2016-08-28 18:09         121.481          31.304   
102357            31.238  2016-08-14 20:28         121.312          31.235   
102360            31.261  2016-08-09 11:01         121.518          31.274   

                                                    track  
972     121.464,31.267#121.465,31.267#121.466,31.267#1...  
1041    121.413,31.199#121.414,31.198#121.414,31.199#1...  
1133    121.381,31.251#121.382,31.246#121.382,31.251#1...  
1204    121.414,31.269#121.415,31.265#121.415,31.266#1...  
1374    121.411,31.186#121.412,31.186#121.413,31.186#1...  
...                                                   ...  
102354  121.498,31.287#121.498,31.288#121.499,31.287#1...  
102355  121.518,31.311#121.519,31.311#121.519,31.312#1...  
102356  121.478,31.297#121.479,31.297#121.480,31.297#1...  
102357  121.312,31.235#121.313,31.235#121.313,31.236#1...  
102360  121.518,31.274#121.519,31.270#121.519,31.271#1...  

[23299 rows x 10 columns]

In [70]:
gxdc.drop_duplicates()

orderid  bikeid  userid        start_time  start_location_x  \
0         78387  158357   10080  2016-08-20 06:57           121.348   
1        891333   92776    6605  2016-08-29 19:09           121.508   
2       1106623  152045    8876  2016-08-13 16:17           121.383   
3       1389484  196259   10648  2016-08-23 21:34           121.484   
4        188537   78208   11735  2016-08-16 07:32           121.407   
...         ...     ...     ...               ...               ...   
102356  1479550  214335    1423  2016-08-28 18:03           121.478   
102357  1478273  160487    3067  2016-08-14 20:22           121.320   
102358   367733  179530   12746  2016-08-27 09:54           121.391   
102359    64915  167419     837  2016-08-20 06:04           121.515   
102360   326987   63172    2547  2016-08-09 10:51           121.521   

        start_location_y          end_time  end_location_x  end_location_y  \
0                 31.389  2016-08-20 07:04         121.357          31.388   
1                 31.279  2016-08-29 19:31         121.489          31.271   
2                 31.254  2016-08-13 16:36         121.405          31.248   
3                 31.320  2016-08-23 21:43         121.471          31.325   
4                 31.292  2016-08-16 07:41         121.418          31.288   
...                  ...               ...             ...             ...   
102356            31.297  2016-08-28 18:09         121.481          31.304   
102357            31.238  2016-08-14 20:28         121.312          31.235   
102358            31.307  2016-08-27 10:06         121.398          31.306   
102359            31.269  2016-08-20 06:10         121.510          31.272   
102360            31.261  2016-08-09 11:01         121.518          31.274   

                                                    track  
0       121.347,31.392#121.348,31.389#121.349,31.390#1...  
1       121.489,31.270#121.489,31.271#121.490,31.270#1...  
2       121.381,31.251#121.382,31.251#121.382,31.252#1...  
3       121.471,31.325#121.472,31.325#121.473,31.324#1...  
4       121.407,31.291#121.407,31.292#121.408,31.291#1...  
...                                                   ...  
102356  121.478,31.297#121.479,31.297#121.480,31.297#1...  
102357  121.312,31.235#121.313,31.235#121.313,31.236#1...  
102358  121.390,31.307#121.391,31.307#121.392,31.307#1...  
102359  121.510,31.272#121.510,31.273#121.511,31.273#1...  
102360  121.518,31.274#121.519,31.270#121.519,31.271#1...  

[102361 rows x 10 columns]

In [71]:
gxdc.drop_duplicates(subset='bikeid')

orderid  bikeid  userid        start_time  start_location_x  \
0         78387  158357   10080  2016-08-20 06:57           121.348   
1        891333   92776    6605  2016-08-29 19:09           121.508   
2       1106623  152045    8876  2016-08-13 16:17           121.383   
3       1389484  196259   10648  2016-08-23 21:34           121.484   
4        188537   78208   11735  2016-08-16 07:32           121.407   
...         ...     ...     ...               ...               ...   
102351   657156   59970    5497  2016-08-31 09:09           121.372   
102352   186351   24298   11196  2016-08-11 07:42           121.422   
102353  1168582  322536   15738  2016-08-26 09:03           121.473   
102358   367733  179530   12746  2016-08-27 09:54           121.391   
102359    64915  167419     837  2016-08-20 06:04           121.515   

        start_location_y          end_time  end_location_x  end_location_y  \
0                 31.389  2016-08-20 07:04         121.357          31.388   
1                 31.279  2016-08-29 19:31         121.489          31.271   
2                 31.254  2016-08-13 16:36         121.405          31.248   
3                 31.320  2016-08-23 21:43         121.471          31.325   
4                 31.292  2016-08-16 07:41         121.418          31.288   
...                  ...               ...             ...             ...   
102351            31.119  2016-08-31 09:23         121.375          31.107   
102352            31.201  2016-08-11 07:46         121.420          31.197   
102353            31.193  2016-08-26 09:10         121.471          31.202   
102358            31.307  2016-08-27 10:06         121.398          31.306   
102359            31.269  2016-08-20 06:10         121.510          31.272   

                                                    track  
0       121.347,31.392#121.348,31.389#121.349,31.390#1...  
1       121.489,31.270#121.489,31.271#121.490,31.270#1...  
2       121.381,31.251#121.382,31.251#121.382,31.252#1...  
3       121.471,31.325#121.472,31.325#121.473,31.324#1...  
4       121.407,31.291#121.407,31.292#121.408,31.291#1...  
...                                                   ...  
102351  121.372,31.118#121.372,31.119#121.373,31.117#1...  
102352  121.419,31.200#121.419,31.201#121.420,31.199#1...  
102353  121.473,31.193#121.473,31.194#121.473,31.196#1...  
102358  121.390,31.307#121.391,31.307#121.392,31.307#1...  
102359  121.510,31.272#121.510,31.273#121.511,31.273#1...  

[79062 rows x 10 columns]

In [77]:
df=pd.DataFrame([[1,np.nan,2,3,4],[np.nan,5,6,7],[8,9,10,np.nan],[11,np.nan,np.nan,12]],columns=['A','B','C','D','E'])
df

A    B     C     D    E
0   1.0  NaN   2.0   3.0  4.0
1   NaN  5.0   6.0   7.0  NaN
2   8.0  9.0  10.0   NaN  NaN
3  11.0  NaN   NaN  12.0  NaN

In [78]:
df.fillna(0)

A    B     C     D    E
0   1.0  0.0   2.0   3.0  4.0
1   0.0  5.0   6.0   7.0  0.0
2   8.0  9.0  10.0   0.0  0.0
3  11.0  0.0   0.0  12.0  0.0

In [81]:
df=pd.DataFrame([[1,np.nan,2,3,4],[np.nan,5,6,7],[8,9,10,np.nan],[11,np.nan,np.nan,12]],columns=['A','B','C','D','E'])
df

A    B     C     D    E
0   1.0  NaN   2.0   3.0  4.0
1   NaN  5.0   6.0   7.0  NaN
2   8.0  9.0  10.0   NaN  NaN
3  11.0  NaN   NaN  12.0  NaN

In [80]:
df.fillna(method='ffill')

A    B     C     D    E
0   1.0  NaN   2.0   3.0  4.0
1   1.0  5.0   6.0   7.0  4.0
2   8.0  9.0  10.0   7.0  4.0
3  11.0  9.0  10.0  12.0  4.0

In [82]:
df=pd.DataFrame([[1,np.nan,2,3,4],[np.nan,5,6,7],[8,9,10,np.nan],[11,np.nan,np.nan,12]],columns=['A','B','C','D','E'])
df

A    B     C     D    E
0   1.0  NaN   2.0   3.0  4.0
1   NaN  5.0   6.0   7.0  NaN
2   8.0  9.0  10.0   NaN  NaN
3  11.0  NaN   NaN  12.0  NaN

In [83]:
df.fillna(method='bfill')

A    B     C     D    E
0   1.0  5.0   2.0   3.0  4.0
1   8.0  5.0   6.0   7.0  NaN
2   8.0  9.0  10.0  12.0  NaN
3  11.0  NaN   NaN  12.0  NaN

In [84]:
df=pd.DataFrame([[1,np.nan,2,3,4],[np.nan,5,6,7],[8,9,10,np.nan],[11,np.nan,np.nan,12]],columns=['A','B','C','D','E'])
df

A    B     C     D    E
0   1.0  NaN   2.0   3.0  4.0
1   NaN  5.0   6.0   7.0  NaN
2   8.0  9.0  10.0   NaN  NaN
3  11.0  NaN   NaN  12.0  NaN

In [85]:
df.fillna(value={'A':0,'B':88,'C':666,'D':888})

A     B      C      D    E
0   1.0  88.0    2.0    3.0  4.0
1   0.0   5.0    6.0    7.0  NaN
2   8.0   9.0   10.0  888.0  NaN
3  11.0  88.0  666.0   12.0  NaN

In [87]:
df=pd.DataFrame([[1,np.nan,2,3,4],[np.nan,5,6,7],[8,9,10,np.nan],[11,np.nan,np.nan,12]],columns=['A','B','C','D','E'])
df

A    B     C     D    E
0   1.0  NaN   2.0   3.0  4.0
1   NaN  5.0   6.0   7.0  NaN
2   8.0  9.0  10.0   NaN  NaN
3  11.0  NaN   NaN  12.0  NaN

In [86]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [89]:
ly.head()

Unnamed: 0 出发地   目的地     价格      节省  \
0           0  哈尔滨   北海  2208.0  650.0   
1           1   成都  泸沽湖  1145.0  376.0   
2           2   广州   沈阳  2702.0  618.0   
3           3   上海  九寨沟  1954.0  484.0   
4           4   广州   天津  1608.0  422.0   

                                       路线名                       酒店  \
0     哈尔滨-北海3天2晚 | 入住北海祥丰嘉年华大酒店 + 春秋航空往返机票   北海祥丰嘉年华大酒店 舒适型 4.7分/5分   
1    成都-泸沽湖3天2晚 | 入住7天酒店丽江古城中心店 + 成都航空往返机票  7天酒店丽江古城中心店 经济型 4.0分/5分   
2     广州-沈阳3天2晚 | 入住沈阳中煤宾馆 + 南方航空/深圳航空往返机票       沈阳中煤宾馆 舒适型 4.5分/5分   
3        上海-九寨沟3天2晚 | 入住红原芸谊大酒店 + 成都航空往返机票      红原芸谊大酒店 舒适型 4.6分/5分   
4  广州-天津3天2晚 | 入住天津逸海明珠大酒店 + 奥凯航空/海南航空往返机票    天津逸海明珠大酒店 高档型 4.1分/5分   

                           房间         去程航司 去程方式         去程时间         回程航司  \
0       标准双人间(双床) 双床 不含早 1间2晚  春秋航空 9C8741   直飞  17:10-21:50  春秋航空 9C8742   
1  经济房-不含早-限时特... 其他 不含早 1间2晚  成都航空 EU2237   直飞  19:45-21:20  成都航空 EU2738   
2          大床间(内宾) 大床 双早 1间2晚  南方航空 CZ6384   直飞  08:05-11:45  深圳航空 ZH9652   
3        豪华双床房[双早] 双床 双早 1间2晚  成都航空 EU6678   直飞  21:55-01:15  成都航空 EU6677   
4       豪华双床房(预付) 双床 不含早 1间2晚  奥凯航空 BK2787   直飞  06:55-10:00  海南航空 HU7201   

  回程方式          回程时间  
0    直飞  10:20-15:05  
1    直飞  23:30-01:05  
2    经停  08:20-13:05  
3    直飞  17:45-20:35  
4    直飞  20:15-23:25

In [99]:
ly.columns

Index(['Unnamed: 0', '出发地 ', ' 目的地', '价格 ', '节省', '路线名', '酒店', '房间', '去程航司',
       '去程方式', '去程时间', '回程航司', '回程方式 ', '回程时间'],
      dtype='object')

In [103]:
ly

出发地   目的地     价格      节省                                          路线名  \
0     哈尔滨   北海  2208.0  650.0         哈尔滨-北海3天2晚 | 入住北海祥丰嘉年华大酒店 + 春秋航空往返机票   
1      成都  泸沽湖  1145.0  376.0        成都-泸沽湖3天2晚 | 入住7天酒店丽江古城中心店 + 成都航空往返机票   
2      广州   沈阳  2702.0  618.0         广州-沈阳3天2晚 | 入住沈阳中煤宾馆 + 南方航空/深圳航空往返机票   
3      上海  九寨沟  1954.0  484.0            上海-九寨沟3天2晚 | 入住红原芸谊大酒店 + 成都航空往返机票   
4      广州   天津  1608.0  422.0      广州-天津3天2晚 | 入住天津逸海明珠大酒店 + 奥凯航空/海南航空往返机票   
...   ...  ...     ...    ...                                          ...   
5095   宁波  九寨沟  2085.0  562.0  宁波-九寨沟3天2晚 | 入住黑水县达古冰山国际大酒店 + 成都航空/四川航空往...   
5096   成都  泸沽湖  1158.0  376.0            成都-泸沽湖3天2晚 | 入住丽江望月阁客栈 + 成都航空往返机票   
5097   天津   丽江  1616.0  426.0  天津-丽江3天2晚 | 入住丽江凡间度假连锁客栈青旅店 + 天津航空/首都航空往...   
5098   大连   重庆  1703.0  446.0      大连-重庆3天2晚 | 入住重庆酉阳锦宏大酒店 + 华夏航空/山东航空往返机票   
5099   天津  哈尔滨  1192.0  356.0    天津-哈尔滨3天2晚 | 入住哈尔滨钰轩酒店中央大街店 + 奥凯航空/福州往返机票   

                             酒店                          房间         去程航司 去程方式  \
0        北海祥丰嘉年华大酒店 舒适型 4.7分/5分       标准双人间(双床) 双床 不含早 1间2晚  春秋航空 9C8741   直飞   
1       7天酒店丽江古城中心店 经济型 4.0分/5分  经济房-不含早-限时特... 其他 不含早 1间2晚  成都航空 EU2237   直飞   
2            沈阳中煤宾馆 舒适型 4.5分/5分          大床间(内宾) 大床 双早 1间2晚  南方航空 CZ6384   直飞   
3           红原芸谊大酒店 舒适型 4.6分/5分        豪华双床房[双早] 双床 双早 1间2晚  成都航空 EU6678   直飞   
4         天津逸海明珠大酒店 高档型 4.1分/5分       豪华双床房(预付) 双床 不含早 1间2晚  奥凯航空 BK2787   直飞   
...                         ...                         ...          ...  ...   
5095   黑水县达古冰山国际大酒店 豪华型 3.9分/5分      B区豪华标间(双床) 双床 不含早 1间2晚  成都航空 EU2730   经停   
5096        丽江望月阁客栈 经济型 4.6分/5分  标准双人间-不含早（预... 双床 不含早 1间2晚  成都航空 EU2237   直飞   
5097  丽江凡间度假连锁客栈青旅店 经济型 4.5分/5分          大床房-预付 大床 不含早 1间2晚  天津航空 GS7861   直飞   
5098      重庆酉阳锦宏大酒店 舒适型 4.0分/5分         特惠房(大床) 大床 不含早 1间2晚  华夏航空 G52762   经停   
5099   哈尔滨钰轩酒店中央大街店 舒适型 4.0分/5分         标准大床房 大床 大床 双早 1间2晚  奥凯航空 BK2918   直飞   

             去程时间         回程航司 回程方式          回程时间  
0     17:10-21:50  春秋航空 9C8742    直飞  10:20-15:05  
1     19:45-21:20  成都航空 EU2738    直飞  23:30-01:05  
2     08:05-11:45  深圳航空 ZH9652    经停  08:20-13:05  
3     21:55-01:15  成都航空 EU6677    直飞  17:45-20:35  
4     06:55-10:00  海南航空 HU7201    直飞  20:15-23:25  
...           ...          ...   ...          ...  
5095  19:45-00:45  四川航空 3U8927    经停  07:55-12:15  
5096  19:45-21:20  成都航空 EU2738    直飞  23:30-01:05  
5097  16:25-19:45  首都航空 JD5739    直飞  07:50-10:50  
5098  18:25-23:30  山东航空 SC4837    经停  07:00-11:30  
5099  21:10-23:25    福州 FU6556    直飞  11:35-13:45  

[5100 rows x 13 columns]